begin;
create table public.navigation_pages (
  id bigint generated by default as identity primary key,
  label text not null check (char_length(trim(label)) between 1 and 100),
  href text not null default '' check (href in ('', '/questions', '/interview', '/projects')),
  body text not null default '' check (char_length(body) <= 20000),
  sort_order integer not null default 0 check (sort_order between 0 and 9999),
  is_public boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into public.navigation_pages(label, body, sort_order, is_public)
  select '自己紹介', bio, 0, true from public.site_profile where id = 1;
insert into public.navigation_pages(label, href, sort_order, is_public) values
  ('質問コーナー', '/questions', 1, true),
  ('Interview Q&A', '/interview', 2, true),
  ('Projects', '/projects', 3, true);
alter table public.navigation_pages enable row level security;
revoke all on public.navigation_pages from anon, authenticated;
grant select on public.navigation_pages to anon, authenticated;
grant insert, update, delete on public.navigation_pages to authenticated;
grant usage, select on sequence public.navigation_pages_id_seq to authenticated;
create policy "Public navigation" on public.navigation_pages for select to anon, authenticated using (is_public);
create policy "Admins manage navigation" on public.navigation_pages for all to authenticated
  using (exists (select 1 from public.admins where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admins where user_id = (select auth.uid())));
create trigger navigation_updated before update on public.navigation_pages
  for each row execute function public.set_updated_at();
commit;
